---
- hosts: localhost
  vars:
    mysql_host: '{{ ansible_env.MYSQL_PORT_3306_TCP_ADDR }}'
    mysql_root: '{{ ansible_env.MYSQL_ENV_MYSQL_ROOT_PASSWORD }}'
    mysql_user: '{{ ansible_env.MYSQL_RADIUS_USER }}'
    mysql_pass: '{{ ansible_env.MYSQL_RADIUS_USER_PASSWORD }}'
    radius_secret: '{{ ansible_env.RADIUS_SECRET }}'

  tasks:
    - name: Create RADIUS user account
      mysql_user: name={{ mysql_user }} password={{ mysql_pass }} host=% priv=radius.*:ALL,GRANT state=present login_user=root login_password={{ mysql_root }} login_host={{ mysql_host }}

    - name: Create RADIUS database
      mysql_db: name=radius state=present login_user=root login_password={{ mysql_root }} login_host={{ mysql_host }}

    - name: Create RADIUS tables
      shell: mysql -u{{ mysql_user }} -p{{ mysql_pass }} -h{{ mysql_host }} radius < /etc/freeradius/sql/mysql/{{ item }}
      ignore_errors: True
      with_items:
        - schema.sql
        - nas.sql

    - name: Copy configuration files to remote host
      template: src={{ item }} dest=/etc/freeradius/{{ item }} owner=root group=freerad
      with_items:
        - radiusd.conf
        - clients.conf
        - sql.conf
        - sites-available/default
        - sites-available/inner-tunnel

    - name: Restart RADIUS server
      service: name=freeradius state=stopped

    - name: Create temp dir of ssl private dir
      file: state=directory path=/etc/ssl/private-copy

    - name: Copy /etc/ssl/private/* to /etc/ssl/private-copy/
      shell: mv /etc/ssl/private/* /etc/ssl/private-copy/

    - name: Remove ssl private dir
      file: state=absent path=/etc/ssl/private

    - name: Copy /etc/ssl/private-copy to /etc/ssl/private
      shell: mv /etc/ssl/private-copy /etc/ssl/private

    - name: Set priveledges for ssl private dir
      file: path=/etc/ssl/private mode=0700 owner=freerad

