---
- hosts: localhost

  tasks:
    - name: Add unofficial freeradius repository
      apt_repository: repo='ppa:freeradius/stable' update_cache=yes

    - name: install freeradius packages
      apt: name={{ item }} state=present
      with_items:
        - freeradius
        - freeradius-mysql
        - python-mysqldb
        - mysql-client
